Flask2
frenzymadness/donors_registry pull request #105
Opened 2021-05-18 07:02 UTC by screamy159

Ve všech třech blueprintech jsem změnil `@blueprint.route()` na `@blueprint.get()` nebo `@blueprint.post()` jestli to bylo možné
Mělo by uzavřít #59

V requirements jsem povýšil verze nástrojů

2021-05-18 07:31 UTC, frenzymadness requested changes
Díky, vypadá to dobře. Dopiš prosím komentář k tomu pandasu, aby se v budoucnu někdo marně nepokoušel o update, dokud nezahodíme support pro Python 3.6. Napsal bych to společně s existujícím komentářem nad tu definici pandasu.

2021-05-18 18:48 UTC, adelpopelkova commented
Super, vypadá to dobře. Osobně bych trochu "uklidila commity" - smazala ty, které nejsou nutné. Některé změny by se daly spojit. Ale to rozhodně není nutné, to se dá do jisté míry vyřešit i při začleňování Pull Requestu (PR). 😉
Jedna věc, která by byla fajn, je odkázání na ty Issues tak, aby se se začleněním tohoto PR zavřely i ty Issues. To se dá udělat tak, že použiješ jedno z těchto [klíčových slov](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) buď v commit message commitu, který to Issue řeší, nebo v popisku toho PR, případně tady vpravo je sekce Linked Issues, kde by mělo být možno vybrat issues (nejsem si ale 100% jistá, že to bude fungovat bez oprávnění k zápisu do repozitáře).
A poslední poznámka, nesmíme po začleněné tohoto PR zapomenout zavřít tady tento (https://github.com/frenzymadness/donors_registry/pull/63), který řeší to stejné jen v menším.

2021-05-19 06:35 UTC, Glutexo commented
A neměly by se třeba ty věci řešit zvlášť? Tedy nechat povýšení Flasku #63 v jednom, změnu akcí v druhém, a povyšování ostatních knihoven dát úplně pryč, protože to s tím vůbec nesouvisí a není to potřeba.

2021-05-19 06:52 UTC, frenzymadness commented
> A neměly by se třeba ty věci řešit zvlášť? Tedy nechat povýšení Flasku #63 v jednom, změnu akcí v druhém, a povyšování ostatních knihoven dát úplně pryč, protože to s tím vůbec nesouvisí a není to potřeba.

Povýšení všech závislostí byl můj nápad, když už se do toho hrabe. Nová verze flasku je jen spouštěč. A v tom, že jeden commit implementuje funkcionalitu umožněnou předchozím commitem nevidím problém.

2021-05-19 06:54 UTC, frenzymadness approved these changes
Líbí se mi to. Díky! Uvidíme, jestli manuálně připojené issues merge tohoto PR zavře.

2021-05-19 06:54 UTC, merged

2021-05-19 06:55 UTC, frenzymadness commented
Zavře, dobré to je.