Přidej souhrnnou tabulku dárců
frenzymadness/donors_registry pull request #11
Opened 2020-09-27 08:22 UTC by Glutexo

Nová přehledová tabulka slouží zobrazení všech dárců společně s jejich počtem odběrů podle jednotlivých měst a se získanými medailemi. Jedná se pouze o „pohled“, její obsah se sestavuje z hodnot v ostatních tabulkách.

2020-09-27 11:15 UTC, frenzymadness approved these changes

2020-09-27 15:18 UTC, frenzymadness requested changes
Ještě sloupec pro "Jinde"

2020-09-29 16:38 UTC, Glutexo commented
Máš jej tam.

2020-09-29 17:30 UTC, Glutexo commented
Začlenil jsem větev _master_, opravil konflikt a sloučil databázové migrace.

2020-09-30 12:07 UTC, frenzymadness requested changes
Ještě drobný nesoulad mezi modelem a migrací.

2020-09-30 12:07 UTC, frenzymadness commented on registry/donor/models.py
> +    donation_count_manual = db.Column(db.Integer, nullable=False)
Tento sloupec chybí v db migraci.

2020-10-01 17:02 UTC, Glutexo commented
Tak třetí pokus.

2020-10-01 17:13 UTC, Glutexo commented
Přeskládal jsem na současný _master_. Tím jsem se mohl zbavit sloučení migrací.

2020-10-02 07:42 UTC, frenzymadness approved these changes

2020-10-02 07:42 UTC, merged