Tlačíko svítí oranžově když dárce nemá nárok
frenzymadness/donors_registry pull request #123
Opened 2021-05-21 12:35 UTC by screamy159

finally close #117

2021-05-21 13:32 UTC, frenzymadness requested changes
Vypadá a funguje to moc dobře. Doplnil bych už jen testy. Např:
1. Načti detail dárce
2. Kolik medailí má, tolikrát by na stránce měl být title "Odebrat medaili"
3. Tolikrát, na kolik medailí má nárok by na stránce mělo být title "Udělit medaili"
4. A nakonec to samé pro "Udělit medaili (Nemá nárok)"

2021-05-21 13:32 UTC, frenzymadness commented on registry/templates/donor/detail.html
> +                            {% if medal.minimum_donations > overview.donation_count_total%}
```suggestion
                            {% if medal.minimum_donations > overview.donation_count_total %}
```

2021-05-26 05:12 UTC, frenzymadness requested changes
Jen několik drobností v testech, jinak to vypadá a funguje velmi dobře.

2021-05-26 05:12 UTC, frenzymadness commented on tests/test_functional.py
> +                medal_amount += 1
Udělené medaile lze zjistit i podstatně snáz.

```suggestion
        login(user, testapp)
        res = testapp.get(url_for("donor.detail", rc=rodne_cislo))
        medal_amount = AwardedMedals.query.filter(AwardedMedals.rodne_cislo == rodne_cislo).count()
```

2021-05-26 05:12 UTC, frenzymadness commented on tests/test_functional.py
> +            db.session.delete(awarded_medal)
Náhodou jsem zjistil, že by to mělo jít i jednodušeji.

```suggestion
        AwardedMedals.query.filter(
            AwardedMedals.rodne_cislo == rodne_cislo
        ).delete()
```

2021-05-26 08:18 UTC, JustScreaMy commented on tests/test_functional.py
> +            db.session.delete(awarded_medal)
Upraveno

2021-05-26 08:18 UTC, screamy159 commented on tests/test_functional.py
> +                medal_amount += 1
Upraveno

2021-05-26 10:22 UTC, frenzymadness approved these changes
Super, nemám co dodat.

2021-05-26 10:22 UTC, merged